src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\OneToMany(mappedBy: 'Categorie', targetEntity: Painting::class)]
    private Collection $paintings;

    public function __construct()
    {
        $this->paintings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection<int, Painting>
     */
    public function getPaintings(): Collection
    {
        return $this->paintings;
    }

    public function addPainting(Painting $painting): self
    {
        if (!$this->paintings->contains($painting)) {
            $this->paintings->add($painting);
            $painting->setCategorie($this);
        }

        return $this;
    }

    public function removePainting(Painting $painting): self
    {
        if ($this->paintings->removeElement($painting)) {
            // set the owning side to null (unless already changed)
            if ($painting->getCategorie() === $this) {
                $painting->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Entity/Painting.php
<?php

namespace App\Entity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\PaintingRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
#[ORM\Entity(repositoryClass: PaintingRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(
    fields: ['Titre'], message: 'cette donnee existe deja',)]
#[Vich\Uploadable]

class Painting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 2,
        max: 255,
        minMessage: 'Votre titre doit contenir au moins {{ limit }} characteres',
        maxMessage: 'Votre titre ne peux pas depasser {{ limit }} characteres',
    )]
    private ?string $Titre = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(
        min: 10,

        minMessage: 'Votre contenu doit avoir au moins {{ limit }} characteres',

    )]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $CreatedAt = null;

    #[ORM\Column]
    #[Assert\Length(
        min: 2,

        minMessage: 'Votre longueur doit avoir au moins {{ limit }} characteres',

    )]
    private ?int $Hauteur = null;

    #[ORM\Column]
    #[Assert\Length(
        min: 2,

        minMessage: 'Votre largeur doit avoir au moins {{ limit }} characteres',

    )]
    private ?int $Largeur = null;

   // #[ORM\Column(length: 255)]
   // private ?string $Image = null;

    #[ORM\ManyToOne(inversedBy: 'paintings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Technique $Technique = null;

    #[ORM\ManyToOne(inversedBy: 'paintings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $Categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'image', fileNameProperty: 'Image')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image= null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $RegisterAt = null;

    #[ORM\OneToMany(mappedBy: 'relation', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getHauteur(): ?int
    {
        return $this->Hauteur;
    }

    public function setHauteur(int $Hauteur): self
    {
        $this->Hauteur = $Hauteur;

        return $this;
    }

    public function getLargeur(): ?int
    {
        return $this->Largeur;
    }

    public function setLargeur(int $Largeur): self
    {
        $this->Largeur = $Largeur;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
*/
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        //if (null !== $imageFile) {
           // // It is required that at least one field changes if you are using doctrine
          //  // otherwise the event listeners won't be called and the file is lost
          //  $this->updatedAt = new \DateTimeImmutable();
      //  }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getTechnique(): ?Technique
    {
        return $this->Technique;
    }

    public function setTechnique(?Technique $Technique): self
    {
        $this->Technique = $Technique;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function createSlug()
    {

        $slugify = new Slugify();
        $this->slug = $slugify->slugify($this->Titre);


    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getRegisterAt(): ?\DateTimeImmutable
    {
        return $this->RegisterAt;
    }

    public function setRegisterAt(?\DateTimeImmutable $RegisterAt): self
    {
        $this->RegisterAt = $RegisterAt;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setRelation($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getRelation() === $this) {
                $comment->setRelation(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use App\Entity\Comment;
use App\Entity\Painting;
use App\Form\CommentType;
use App\Repository\PaintingRepository;
use App\Repository\CommentRepository;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Faker;

class HomeController extends
    AbstractController
{
    #[Route('/', name: 'home')]
    public function home ( PaintingRepository $repository, CategorieRepository $categorieRepository,
                           PaginatorInterface $paginator,
Request $request ): Response
    {
        $tableau = $repository->findBy([], ['Categorie' => 'ASC']);
        $categorie = $categorieRepository->findAll();
        $pagination = $paginator->paginate(
            $tableau,
            $request->query->getInt('page', 1),
            8
        );
        return $this->render('home/home.html.twig', [
                'home' => $tableau,
                'home' => $pagination,
                'categories'=>$categorie
            ]
        );
    }

    #[Route('home/{slug}', name: 'riri')]
    public function detail (
        Painting               $tableau,
        CommentRepository      $repository,
        Request                $request,
        EntityManagerInterface $manager
    ): Response {
        $faker = Faker\Factory::create('fr_FR');
        $comment = $repository->findBy(['relation' => $tableau], ['createdAt' => 'DESC']);
        $commentaire = new Comment();
        $form = $this->createForm(CommentType::class, $commentaire);
        $form->handleRequest($request);//recupere les donees du formulaire
        if ( $form->isSubmitted() && $form->isValid() ) {
            //  $paint ->setImage('default.png')

            $commentaire->setCreatedAt(new \DateTimeImmutable("now"));
            $commentaire->setRelation($tableau);
            $commentaire->setIsPublished($faker->boolean(90));
            $manager->persist($commentaire);
            $manager->flush();
            $this->addFlash('notice', 'votre commentaire a bien ete ajouté');
            return $this->redirectToRoute('home');
        }
        return $this->render('home/detail.html.twig', [
            'riri' => $tableau,
            'comments' => $comment,
            'form' => $form->createView(),
        ]);
    }
}

templates/home/detail.html.twig
{% extends 'base.html.twig' %}



{% block body %}

    <div class="container" style="padding-top: 150px">
        <div class="row">


            <div class="col-md-6">
                <img class="pb-3" src="{{ asset
                    ('/img/tableau/' ~ riri.image) }}" alt="{{ riri.titre }}"
                     style="width: 300px;height: 200px"/>

                <div>

                        <div class="btn btn-primary mt-5 mb-5" type="button"
                             data-bs-toggle="collapse"
                             data-bs-target="#collapseComment"
                             aria-expanded="false"
                             aria-controls="collapseComment">
                            Voir les commentaires
                        </div>


                    <div class="collapse" id="collapseComment">
                    <div class="card shadow-0 border w-75"
                         style="background-color: #f0f2f5;">
                        <div class="text-center pt-3">
                            {% set count = 0 %}
                            {% for comment in comments %}
                                {% set count = count + 1 %}
                            {% endfor %}
                            {% if count == 0 %}
                                <p class="fs-3">il n'y a pas encore de
                                    commentaire pour cette
                                    oeuvre</p>
                            {% elseif count > 1 %}
                                <p class="fs-3">nombre de
                                    commentaires: {{ count }}</p>
                            {% else %}
                                <p class="fs-3">nombre de
                                    commentaire: {{ count }}</p>
                            {% endif %}
                        </div>
                        {% for comment in comments %}
                            <div class="card-body p-4">


                                <div class="card mb-4">
                                    <div class="card-body">
                                        <p class="fs-6">{{ comment.name }}
                                            &ensp;&ensp;
                                            publié le:&nbsp; {{ comment.createdAt|date
                                                ('d/m/Y') }}</p>

                                        {{ comment.comment }}


                                    </div>
                                </div>


                            </div>
                        {% endfor %}
                    </div>
                </div>

                </div>
            </div>

            <div class="col-md-6 ps-5">

                <h3 class="display-7 text-center text-black-50">{{ riri.titre|upper }}</h3>

                <p class="lead text-center">
                    Descrition de l'oeuvre</p>
                <p class="text-justify"></p>
                {{ riri.description|capitalize }}</p>
                <div class="text-center">
                    <div class="btn btn-primary mt-5" type="button"
                         data-bs-toggle="collapse"
                         data-bs-target="#collapseExample" aria-expanded="false"
                         aria-controls="collapseExample">
                        Ajouter un commentaire
                    </div>
                </div>
                <div class="collapse" id="collapseExample">
                    <div class=" container-fluid mt-4 p-3 w-80"
                         style="background-color:  #f0f2f5">
                        {{ form(form) }}
                    </div>
                </div>

                <div>


                </div>
            </div>

        </div>
    </div>

{% endblock %}

templates/home/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <section id="1">

        <div id="carouselExampleControls" class="carousel slide carousel-fade"
             data-bs-ride="carousel">

            <div class="carousel-inner">

                <div class="carousel-item active" data-bs-interval="10000">

                    <img sizes="w" src="{{ asset
                        ('../../img/brand6.jpeg') }}"
                         class="d-block w-100" alt="..." style="height:350px">
                </div>
                <div class="carousel-item" data-bs-interval="10000">
                    <img src="{{ asset
                        ('../../img/brand7.jpg') }}"
                         class="d-block w-100" alt="..." style="height: 350px">
                </div>
                <div class="carousel-item " data-bs-interval="10000">
                    <img src="{{ asset
                        ('../../img/brand5.jpg') }}"
                         class="d-block w-100" alt="..." style="height: 350px">
                </div>

            </div>


        </div>

    </section>

    <div class="container">
        {% for message in app.flashes('notice') %}
            <div class="alert alert-info">
                {{ message }}
            </div>
        {% endfor %}
        <div class="row justify-content-center align-items-center ">
            <div class="col-md-12 controls-filter pt-5 text-center">
                <ul>
                    <!-- For filtering controls add -->
                    <li data-filter="all" class="btn btn-outline-primary"> All
                        items
                    </li>
                    {% for categorie in categories %}
                        <li data-filter="{{ categorie.id }}" class="btn
                        btn-outline-primary">{{ categorie.name }} </li>
                    {% endfor %}
                </ul>

            </div>

            <div class="filter-container col-md-12 ">
                {% for tableau in home %}
                    <div  class="filtr-item" data-category="{{
                    tableau
                    .categorie.id }}"
                         data-sort="value">
                        <div class="card border-primary text-center
                mt-4 m-lg-3 "

                             style="width:18rem;min-height: 300px !important;">
                            <div class="card-header  mt-2"
                                 style="min-height:
                4rem;">{{ tableau.titre |capitalize }}</div>

                            <div class="card-body ">
                                <p class="card-title text-center"><a
                                            href="{{ path('riri',
                                                {slug:tableau.slug}) }}"><img

                                                src="{{ asset
                                                    ('img/tableau/' ~ tableau.image) }}"

                                                alt="" style="height:180px
"/></a></p>
                                <figcaption
                                        class="card-text text-center "> {{ tableau
                                    .Categorie
                                    .name }}, {{ tableau.Technique.name }}
                                    <br>  {{ tableau
                                        .createdAt|date
                                            ('Y') }}</br>
                                </figcaption>
                                {{ tableau.hauteur ~ ' cm X ' }}
                                {{ tableau.largeur ~ ' cm' }}

                            </div>

                        </div>
                    </div>
                {% endfor %}

            </div>


        </div>
    </div>
    <div class="container">
        <div class="align-items-center">
            {{ knp_pagination_render(home) }}
        </div>
    </div>

    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/jquery.filterizr.min.js') }}"></script>
    <script>
        let filterizd = $('.filter-container').filterizr({
            // options here
        });
    </script>
{% endblock %}